import Layout from "@/components/layout/layout";
import { Button, Form, Select } from "antd";
import Head from "next/head";
import Image from "next/image";
import styled, { createGlobalStyle } from "styled-components";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GlobalStyles />

      <Layout />
    </>
  );
};

const GlobalStyles = createGlobalStyle`
  && body {
    margin: 0;
    padding: 0;
    background-color: white

    font-size: 20px;

    & * {
      color: black;
    }
    
  }

  & .ant-select, & .ant-select-selector {
    background-color: white;
    border-color: black !important;
    border: none;
    border-bottom: 1px solid white;

    &, & * {
      font-size: 1rem;
    }
  }

  && .ant-select-dropdown {
    &, & * {
      color: black !important;
    }
  }
`;

export default Home;
